name: Deploy Backend

on:
  push:
    branches:
      - backend 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install sshpass
        run: sudo apt-get install -y sshpass  # Install sshpass tool

      - name: Deploy to Server via SSH with Password
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ayush@192.168.18.214 << 'EOF'
            cd /home/ayush/project/backend
            git pull origin backend
            source venv/bin/activate  # Activate virtual environment
            pip install -r requirements.txt  # Install dependencies
            python app.py
          EOF
