name: Deploy Backend Locally

on:
  push:
    branches:
      - backend  # Runs when changes are pushed to backend

jobs:
  lint:
    uses: ./.github/workflows/linting.yml  # Call the linting template
    with:
      python_version: '3.12'

  deploy:
    runs-on: self-hosted
    needs: lint  

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Pull Latest Code
        run: |
          cd /home/ayush/project/backend
          git reset --hard origin/backend  # Reset to latest version
          git pull origin backend          # Pull latest changes

      - name: Run Backend Server
        run: |
          cd /home/ayush/project/backend
          source venv/bin/activate  # Use existing virtual environment
          nohup python app.py &  # Start backend in background
