name: Backend CI/CD

on:
  push:
    branches:
      - backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      # - name: Install dependencies
      #   run: |
      #     cd backend
      #     pip install -r requirements.txt

      - name: Run Tests
        run: |
          cd backend
          pytest

      - name: Deploy Backend
        run: |
          echo "Deploying backend..."

  trigger-frontend:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Frontend Pipeline
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          https://api.github.com/repos/Ash2623/python_project/actions/workflows/frontend.yml/dispatches \
          -d '{"ref":"frontend"}'