name: Deploy Backend Locally

on:
  push:
    branches:
      - backend  # Runs when changes are pushed to the backend branch

jobs:
  deploy:
    runs-on: self-hosted  # Use a self-hosted runner instead of GitHub's default runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          cd backend
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run Backend Server
        run: |
          cd backend
          source venv/bin/activate
          nohup python app.py &
