name: Deploy Backend Locally

on:
  push:
    branches:
      - backend  

jobs:
  lint:  
    uses: ./.github/workflows/linting.yml  
    with:
      python_version: '3.12'
    
  deploy:
    runs-on: self-hosted
    needs: lint  

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Pull Latest Code
        run: |
          cd /home/ayush/project/backend
          git reset --hard origin/backend 
          git pull origin backend          
      - name: Run Backend Server
        run: |
          cd /home/ayush/project/backend
          source venv/bin/activate  
          nohup python app.py &  
