name: Deploy Backend Locally

on:
  push:
    branches:
      - backend  # Runs when changes are pushed to backend branch

jobs:
  deploy:
    runs-on: self-hosted  # Use a self-hosted runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Pull Latest Code
        run: |
          cd /home/ayush/project/backend
          git reset --hard origin/backend  # Reset to latest version
          git pull origin backend          # Pull latest changes

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          cd /home/ayush/project/backend
          python -m venv venv
          source venv/bin/activate

      - name: Run Backend Server
        run: |
          cd /home/ayush/project/backend
          source venv/bin/activate
          nohup python app.py &  # Run backend in background
