on:
  push:
    branches:
      - frontend  

jobs:
  lint:
    uses: ./.github/workflows/linting.yml 
    with:
      python_version: '3.12'

  deploy:
    runs-on: self-hosted
    needs: lint 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Pull Latest Code
        run: |
          cd /home/ayush/project/frontend
          git reset --hard origin/frontend
          git pull origin frontend
 
      - name: Kill Existing Frontend Server (if running)
        run: |
          pkill -f "python -m http.server" || true  # Ignore errors if no server is running

      - name: Start Frontend Server
        run: |
          cd /home/ayush/project/frontend
          nohup python -m http.server 8000 &  # Run HTTP server in the background
