name: Deploy Frontend

on:
  push:
    branches:
      - frontend  # Runs when changes are pushed to the frontend branch

jobs:
  deploy:
    runs-on: self-hosted  # Using your self-hosted runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Pull Latest Code
        run: |
          cd /home/ayush/project/frontend
          git reset --hard origin/frontend
          git pull origin frontend

      - name: Restart Frontend Server
        run: |
          cd /home/ayush/project/frontend
          source venv/bin/activate  # Use existing virtual environment
          nohup python app.py &  # Start frontend in the background
