name: Python CI Template

on:
  workflow_call:
    inputs:
      python_version:
        required: true
        type: string

jobs:
  install-lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}

      - name: Install Dependencies & Linters
        run: |
          pip install flake8 black isort pytest  # Install linters

      - name: Run Linting (Flake8)
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics  # Check for critical errors
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics  # Full lint check

      - name: Run Code Formatting (Black & isort)
        run: |
          black . --check
          isort .

      - name: Run Tests
        run: |
          pytest
