name: Python CI Template

on:
  workflow_call:
    inputs:
      python_version:
        required: true
        type: string

jobs:
  install-lint-test:
    runs-on: ubuntu-latest  # Use GitHub-hosted runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}

      - name: Create Virtual Environment
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m ensurepip --upgrade  # Ensure pip is installed
          pip install --upgrade pip setuptools wheel  # Upgrade packaging tools

      - name: Install Dependencies & Linters
        run: |
          source venv/bin/activate
          pip install -r requirements.txt
          pip install flake8 black isort pytest  # Install linters

      - name: Run Linting (Flake8)
        run: |
          source venv/bin/activate
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Run Code Formatting (Black & isort)
        run: |
          source venv/bin/activate
          black . --check --exclude "venv/*"
          isort . --skip venv

      - name: Run Tests
        run: |
          source venv/bin/activate
          pytest

